# list of sensors for which features are calculated
datasets:
 # - accelerometer
 # - accelerometeruncalibrated
 - activities
 # - airplanemode
 # - ambienttemperature
 - application
 # - batterycharge
 # - batterylevel
 - bluetooth
 - cellularnetwork
 # - doze
 # - geomagneticrotationvector
 # - gravity
 # - gyroscope
 # - gyroscopeuncalibrated
 # - headsetplug
 # - light
 # - linearacceleration
 - location
 # - magneticfield
 # - magneticfielduncalibrated
 # - music
 - notification
 # - orientation
 # - pressure
 - proximity
 # - relativehumidity
 # - ringmode
 # - rotationvector
 - screen
 - stepcounter
 # - stepdetector
# - survey
# - timediary
 - touch
 # - userpresence
 - wifi
 - wifinetworks

# whether time diary data should be included in feature generation.
timediary: True

# aggregation window size in minutes
# - it timediary: True, then the window size w is taken with respect to the timediaries timestamp
#   (e.g., if w=30 minutes, then time window spans from 15 minutes before to 15 minutes after a time diary timestamp.
#
#-	if timediary: False, then the entire sensor data timeline is divided into consecutive, non-overlapping intervals
# of fixed length. For example, if `freq` is set to 30 minutes, intervals like [10:00–10:30), [10:30–11:00), and so on are created. Sensor events are assigned to these intervals based on their timestamps, and features are aggregated accordingly.
freq: 10

