countries:
 - cn
 - dk
 - in
 - it
 - mn
 - mx
 - py
 - uk

datasets:
 - accelerometer
 - accelerometeruncalibrated
 - activities
 - airplanemode
 - ambienttemperature
 - applications
 - batterycharge
 - batterylevel
 - bluetooth
 - cellularnetwork
 - doze
 - geomagneticrotationvector
 - gravity
 - gyroscope
 - gyroscopeuncalibrated
 - headsetplug
 - light
 - linearacceleration
 - location
 - magneticfield
 - magneticfielduncalibrated
 - music
 - notification
 - orientation
 - pressure
 - proximity
 - relativehumidity
 - ringmode
 - rotationvector
 - screen
 - stepcounter
 - stepdetector
 - survey
 - timediary
 - touch
 - wifi
 - wifinetworks